version: '2'

services:
  nginx-unit:
    #build: "./"
    image: yousan/nginx-unit
    container_name: nginx-unit
    ports:
      - 8200:8200
      - 8300:8300
    volumes:
      - ./json:/root/json
      - ./run:/var/run
      - ./root:/www/root
      - ./php.ini:/etc/php/7.0/embed/php.ini
#    restart: always

  mysql:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql
